### ISSUE TITLE
Integrate 0x api

### ISSUE THREAD

**Issue by pociej** [golemfactory/onboarding_staging#11]
Investigate how we can use https://0x.org/docs/ for "swap for gas"

**Comment by golmek** [comment]
We got response that we should use:
https://0x.org/docs/category/tx-relay-api

**Comment by golmek** [comment]
to do: ping

**Comment by golmek** [comment]
We got contact to Product Manager on 0x site. We will continue integration efforts.

**Comment by golmek** [comment]
waiting for response from 0x

**Comment by golmek** [comment]
We have confirmation that Tx-Relay-API is serving Gasless Native <-> ERC20 swaps.

**TODO:**
- we might need Proxy server to use 0x API (cannot be used via Browser) -> To be Verified with Ox Contact

**Comment by golmek** [comment]
- Apparently 0x API should work on Browser - bug should be already fixed - We need to test it and if it works we should be unblocked.

**Comment by golmek** [comment]
GLM was added to supported Tokens.

**Comment by golmek** [comment]
0x is not working again. Waiting for response
