### ISSUE TITLE
Integration with PolygonScan & EthereumScan API

### ISSUE THREAD

**Issue by golmek** [golemfactory/onboarding_staging#58]
PolygonScan API might be used on Onboarding Portal in its Free plan to gather information about external Wallets.

Potential Use Case:
- If YagnaWallet param is set in URL, Onboarding Portal can check if provided YagnaWallet is already onboarded (having matic and glm tokens) ale based on that change the user flow

**Acceptance Criteria:**
- When YagnaWallet is provided as parameter then Onboarding Portal checks if Yagna Wallet has Matic & GLM tokens (Netwok == Polygon)
  - Matic == NO, GLM == NO -> move user through standard onboarding flow.
  - Matic == YES, GLM == NO -> move user through standard onboarding flow Transfer to Yagna is limited to GLM only
  - Matic == NO, GLM == YES -> move user through RAMP without QuickSwap. Transfer to Yagna is limited to Matic only
  - Matic == YES, GLM == YES ->  jump directly to "All is good"page with information that "Your Yagna wallet is already filled with Matic and GLM"
- Same approach as above should be done for Ethereum Network and EthereumScanAPI

**Additional Information:**
- https://polygonscan.com/apis

**Comment by golmek** [comment]
@pociej Shouldn't we think about some proxy endpoint to hide our API keys? I think that this question should be consider for RAMP API key as well.

**Comment by golmek** [comment]
In progress

**Comment by golmek** [comment]
We might use RPC node to get necessary information instead of PolygonScan/EthereumScan

**Comment by pociej** [comment]
closing as it is handled using RPC
